ranches:
env:
  global:
    - REPO: docker-centos6.8-base
    - VERSION: $TRAVIS_BRANCH

sudo: required
services:
- docker
before_install:
- docker build -t ${TRAVIS_JOB_ID} .
- docker build -t ${TRAVIS_JOB_ID}:goss tests/.

install:
- docker run -d --name ${REPO} ${TRAVIS_JOB_ID}:goss
script:
- docker ps | grep -q ${REPO}
- ./tests/goss.sh

