services:
- docker
before_install:
- docker build -t "${TRAVIS_BUILD_DIR}" .
- docker build -t "${TRAVIS_BUILD_DIR}":goss tests/.

install:
- docker run -d --name "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR}":goss
script:
- docker ps | grep -q "${TRAVIS_BUILD_DIR}"
- ./tests/goss.sh

