services:
- docker
before_install:
- docker build -t "${TRAVIS_BRANCH}" .
- docker build -t "${TRAVIS_BRANCH}":goss tests/.

install:
- docker run -d --name "${TRAVIS_BRANCH}" "${TRAVIS_BRANCH}":goss
script:
- docker ps | grep -q "${TRAVIS_BRANCH}"
- ./tests/goss.sh

