services:
- docker
before_install:
- docker build -t docker-centos6.8-base .
- docker build -t docker-centos6.8-base:goss tests/.

install:
- docker run -d --name base docker-centos6.8-base:goss
script:
- docker ps | grep -q base
- docker ps | grep healthy
